[build]
beforeDevCommand = ""
beforeBuildCommand = ""
devPath = "../dist"
distDir = "../dist"

[package]
productName = "replit"
version = "1.0.0"

[tauri]
allowlist = { all = true }

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = []
icon = ["png/icon_512.png"]
identifier = "dev.markwalters.replit"
longDescription = ""
resources = []
shortDescription = ""
targets = ["deb", "appimage"]

[tauri.security]
csp = ""

[tauri.windows]
title = "Replit"
url = "https://replit.com"
width = 1200
height = 780
resizable = true
fullscreen = false
